### ISSUE TITLE
How to add memory hooks on RAM region of memory

### ISSUE THREAD

**Issue by hallhu1** [fuzzware-fuzzer/hoedur#10]
Dear Hoedur developers,

I would like to add memory hooks to detect reads on RAM but I noticed the existing memory hooks in the hoedur implementation do not implement this feature. I have tried looking into functions in the QEMU API, as well as making my own modifications to the underlying QEMU C code, but have come up empty handed thus far. Any suggestions on how to achieve this goal?

**Comment by SWW13** [comment]
RAM hooks are implemented, they just require the fuzzer to run in trace mode.

See https://github.com/fuzzware-fuzzer/hoedur/blob/main/emulator/src/lib.rs#L675-L695 or https://github.com/fuzzware-fuzzer/hoedur-experiments/blob/main/04-prev-unknown-vulns/scripts/hook-trace.rn.
