### ISSUE TITLE
Question: Extending MMIO input and Different Coverage Weights

### ISSUE THREAD

**Issue by Shangzewen** [fuzzware-fuzzer/hoedur#12]
Hi @SWW13 , we would like to do some changes to Hoedur code to support extra features, but we would like to check if you have any feedback or pointers to where in the code we can look to perform such changes.

1. While executing the input file, normally Hoedur ends the input session because it reached the end of contexts (pc,length, mmio addr, etc). The idea here is that if a new context is found, but it contains a MMIO which has been previously accessed, we just pass the same value to this new context. In the case that a new context contains a never seen MMIO address, we simply write a constant value (or buffer) that we decide. Therefore, I was wondering where in the code we could implement a feature that could force the input execution to continue when new context is found. This would help us see where the firmware goes even if imprecision will happen during emulation. 
2. We note that during fuzzing hoedur might not focus on important branches (to us, as we know the firmware application) because it aims to increase overall coverage. How could we best modify the metrics in the coverage class such that certain basic blocks (i.e., specific function) increases the score of the coverage process such that hoedur do not discard this input from the fuzzing process?

**Comment by SWW13** [comment]
Regarding 1, Hoedur already does random extension at the end of input streams and on new input streams. I don't think manually extending the input does help in any way. If you want to continue after the end of input you either have to hack it into the input file random extension or in the emulator and you will likely lose the ability to correctly replay inputs.

Regarding 2, I haven't implemented any form of directed fuzzing in Hoedur so I can't give you any meaningful help here. Coverage guidance in Hoedur is similar to AFL/LibFuzzer, we use a combination of edge `hash(previous pc | next pc)` and hit count as coverage, so can not simply use a known pc to focus an. For each edge+hit-bucket combination at least on input is already kept in the corpus. Increasing the score does not alter which input is kept, it increases the chance to use this input as base for the next mutations.

**Comment by Shangzewen** [comment]
Hi @SWW13 
Thanks a lot for the fast response! 
Regards
Zewen
