### ISSUE TITLE
Failed to take hardware result with current input file: input file missing

### ISSUE THREAD

**Issue by B03901108** [fuzzware-fuzzer/hoedur#4]
Dear Hoedur authors,

I installed hoedur locally and copied the 3DPrinter directory in hoedur-experiments to hoedur.
(i.e., `hoedur-experiments/targets/arm/unpatched-est-data-set/uEmu/3Dprinter/` -> `hoedur/3Dprinter`)
Then, I set $CONFIG and ran `cargo run --bin hoedur-arm -- --config $CONFIG fuzz`.
The fuzzer immediately terminated with the following error:
`emulator - Failed to take hardware result with current input file: input file missing`.
I attempted to resolve this by copying the base_inputs directory in Fuzzware to the 3DPrinter directory, but in vain.
How could I resolve this error? Did I set up the directory correctly for testing an embedded system firmware?
I hope the solution does not involve Docker. Thank you so much.

**Comment by B03901108** [comment]
I circumvented the error by calling `~/.cargos/bin/hoedur-arm` instead. I still wonder about why this error occurred.

Also, can Hoedur print the basic blocks covered in real time, just like Fuzzware, without modifications? I could only obtain these statistics after fuzzing using `hoedur-arm run-cov` and `fuzz-coverage-list.py`. Thank you so much.

**Comment by SWW13** [comment]
I have never seen this issue before, it looks like an internal emulator issue. If you are using your own environment there are a lot of things that could potentially cause this.

If you want to dig into it there should be a `hoedur.log` file in your current working dir after a crash with more details. You can also build debug version (no `--release`) and use the `--log-config common/log/debug.yml` for more details.

**Comment by B03901108** [comment]
@SWW13 Great thanks. I'll dig into the log. Does Hoedur provide an option to print the covered BBs in real-time?

**Comment by SWW13** [comment]
I was able to reproduce and fix the issue in 2547c809750e55cac3172de06ba147d6f371c663.

Printing coverage in real-time is not implemented, as we use coverage only after a fuzzing run due to the high performance overhead of running an instrumented firmware. (Coverage collection is only possible with `--trace` which will hook every basic block)

**Comment by B03901108** [comment]
@SWW13 I have locally built and tested the latest Hoedur. The issue no longer exists. Thank you.
