### ISSUE TITLE
How to parse Hoedur traces?

### ISSUE THREAD

**Issue by B03901108** [fuzzware-fuzzer/hoedur#5]
Hi, how can I make Hoedur traces human-readable? Thank you.
I obtained a trace by running the command
`hoedur-arm --import-config=./Hoedur.corpus.tar.zst  --debug --trace --trace-file=./tmp.trace run <input>`.
As the trace seemed zstd-compressed, I decompressed it with `zstd --decompress`.
The output is not human-readable, so I guess either the trace is binary or my decompression went wrong.

**Comment by SWW13** [comment]
The trace is indeed a binary format automatically created by `bincode`, see `frametracer/src/bintrace.rs` for the corresponding structs.

**Comment by B03901108** [comment]
@SWW13 Should bincode's deserialization make the decompressed trace human-readable? I tried to decompress and then deserialize the trace with the following script but got nothing.

`use std::{fs::File, io::{BufReader, Read}};`
`use anyhow::{Context, Result};`
`use bincode::deserialize_from;`
`use zstd::stream::read::Decoder;`

`fn main() -> Result<()> {`
`    let trace_file = File::open("./Hoedur.trace.bin.zst").with_context(|| "Failed to open the trace")?;`
`    let mut decoder = Decoder::new(BufReader::new(trace_file)).with_context(|| "Failed to create the decoder")?;`
`    let mut decompressed = Vec::new();`
`    decoder.read_to_end(&mut decompressed).with_context(|| "Failed to decompress the trace")?;`
`    let deserialized: Vec<u8> = deserialize_from(&decompressed[..]).with_context(|| "Failed to deserialize the trace")?;`
`    println!("[Trace Output] {:?}", deserialized);`
`    Ok(())`
`}`

**Comment by B03901108** [comment]
I got readable traces using Trace::read_from(&mut decoder) and println("{:08x?}", event).
Great thanks for mentioning `frametracer/src/bintrace.rs`.

`use std::{fs::File, io::BufReader};`
`use anyhow::{Context, Result};`
`use zstd::stream::read::Decoder;`
`use frametracer::Trace;`

`fn main() -> Result<()> {`
`    let trace_file = File::open("./Hoedur.trace.bin.zst").with_context(|| "Failed to open the trace")?;`
`    let mut decoder = Decoder::new(BufReader::new(trace_file)).with_context(|| "Failed to set up the decoder")?;`
`    let traces = Trace::read_from(&mut decoder).with_context(|| "Failed to load the trace")?;`

`    println!("{} traces loaded", traces.len());`
`    for t in traces {`
`        println!("{} events recorded", t.events.len());`
`        for ev in t.events { println!("{:08x?}", ev); }`
`    }`
`    Ok(())`
`}`
