### ISSUE TITLE
Recompile the modified QEMU for Hoedur's use

### ISSUE THREAD

**Issue by hallhu1** [fuzzware-fuzzer/hoedur#9]
Dear Hoedur developers,
I modified the QEMU C code in hoedur/target/release/build/qemu-sys-9b1053f9f61789cc/out/qemu-7.1.0. How to recompile this QEMU for Hoedur and apply the change? I hope the required steps would not reverse the changes I made to the Hoedur code. Thank you so much.

**Comment by SWW13** [comment]
QEMU is build in the [`build.rs`](https://github.com/fuzzware-fuzzer/hoedur/blob/main/qemu-sys/build.rs) file of `qemu-sys`, you can either add a new patch file there or overwork the complete build process to your liking.
